# https://www.youtube.com/watch?v=S2YFqf4L7l8&t=344s

nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

www:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /Users/josemanuelfranciscoaliaga/Documents/GitHub/peladotrack_freelance/01:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=joealiaga.com,www.joealiaga.com
