nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /Users/josemanuelfranciscoaliaga/Documents/GitHub/peladotrack_freelance/01/cert:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
  labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  volumes:
    - /Users/josemanuelfranciscoaliaga/Documents/GitHub/peladotrack_freelance/01/cert:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy:rw

www:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /Users/josemanuelfranciscoaliaga/Documents/GitHub/peladotrack_freelance/01/:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=joealiaga.com,www.joealiaga.com
    - LETSENCRYPT_HOST=joealiaga.com,www.joealiaga.com
    - LETSENCRTPY_EMAIL=jmfaliaga@gmail.com

